version : "3"
services:
    customerapp:
        restart: always
        build:
            dockerfile: Dockerfile-prod
            context: ./CustomerApp
        ports:
            - "4004:8004"
    customerapp_1:
        restart: always
        build:
            dockerfile: Dockerfile-prod
            context: ./CustomerApp
        ports:
            - "5004:8004"
    inventoryapp:
        restart: always
        build:
            dockerfile: Dockerfile-prod
            context: ./InventoryApp
        ports:
            - "4003:8003"
    inventoryapp_1:
        restart: always
        build:
            dockerfile: Dockerfile-prod
            context: ./InventoryApp
        ports:
            - "5003:8003"
    billapp:
        restart: always
        build:
            dockerfile: Dockerfile-prod
            context: ./BillingApp
        ports:
            - "4002:8002"
    billapp_1:
        restart: always
        build:
            dockerfile: Dockerfile-prod
            context: ./BillingApp
        ports:
            - "5002:8002"
    
    bookkeepingapp:
        restart: always
        build:
            dockerfile: Dockerfile-prod
            context: ./BookKeepingApp
        ports:
            - "4001:8001"
    bookkeepingapp_1:
        restart: always
        build:
            dockerfile: Dockerfile-prod
            context: ./BookKeepingApp
        ports:
            - "5001:8001"