FROM maven:3.5-jdk-8-alpine AS buildphase
WORKDIR /usr
COPY ../ .
RUN mvn install

FROM openjdk:8-jdk-alpine
ARG JAR_FILE="/usr/target/InventoryApp-0.0.1-SNAPSHOT.jar"
WORKDIR ./usr
COPY --from=buildphase ${JAR_FILE} InventoryApp.jar
ENTRYPOINT ["java","-jar","InventoryApp.jar"]